apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: bgpconfigurations.crd.projectcalico.org
spec:
    scope: Cluster
    group: crd.projectcalico.org
    versions:
        - name: v1
          served: true
          storage: true
    names:
        kind: BGPConfiguration
        plural: bgpconfigurations
        singular: bgpconfiguration