apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: networksets.crd.projectcalico.org
spec:
    scope: Namespaced
    group: crd.projectcalico.org
    versions:
        - name: v1
          served: true
          storage: true
    names:
        kind: NetworkSet
        plural: networksets
        singular: networkset